# curl -sSL https://raw.githubusercontent.com/infoparticle/useful-scripts/refs/heads/main/scripts/dotfiles/tools.tmux/dot_tmux.conf
set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -sg escape-time 3

set -g base-index 1
setw -g pane-base-index 1

bind r source-file ~/.tmux.conf \; display "Reloaded!"
bind-key M split-window -h "vim ~/.tmux.conf"

# toggle status bar (instead of time)
bind t set -g status

bind | split-window -h
bind - split-window -v

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R
bind -r C-h select-window -t :-
bind -r C-l select-window -t :+

bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

bind-key M choose-tree -Zw "join-pane -t '%%'"
bind-key C-m choose-tree -Zs "join-pane -t '%%'"

# --- Mouse ---
set -g mouse on
bind -n WheelUpPane if-shell -F -t = "#{mouse_any_flag}" "send-keys -M" "if -Ft= '#{pane_in_mode}' 'send-keys -M' 'select-pane -t=; copy-mode -e; send-keys
-M'"
bind -n WheelDownPane select-pane -t= \; send-keys -M
bind -n C-WheelUpPane select-pane -t= \; copy-mode -e \; send-keys -M
bind -T copy-mode-vi    C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-vi    C-WheelDownPane send-keys -X halfpage-down
bind -T copy-mode-emacs C-WheelUpPane   send-keys -X halfpage-up
bind -T copy-mode-emacs C-WheelDownPane send-keys -X halfpage-down

# --- fzf tmux ---
bind-key 0 run "tmux split-window -l 12 'bash -ci ftpane'"
bind-key Tab run "tmux split-window -l 12 'bash -ci ftsession'"

# --- Colors (Dracula) ---
set -g default-terminal "screen-256color"
set-option -g renumber-windows on

# pane border
set -g pane-border-style fg='#6272a4'
set -g pane-active-border-style fg='#ff79c6'

# message text
set -g message-style bg='#44475a',fg='#8be9fd'

set -g status-style bg='#44475a',fg='#bd93f9'
set -g status-interval 1

# status left
set -g status-left-length '100'
set -g status-left '#[bg=#f8f8f2]#[fg=#282a36] #S #[bg=#44475a]#[fg=#f8f8f2]'

# zoomed indicator
set -ga status-left '#[bg=#44475a]#[fg=#ff79c6] #{?window_zoomed_flag,[Z],   }'

# window status
set-window-option -g window-status-style fg='#bd93f9',bg=default
set-window-option -g window-status-current-style fg='#ff79c6',bg='#282a36'

set -g window-status-current-format "#[fg=#44475a]#[bg=#bd93f9]#[fg=black]#[bg=#bd93f9] #I #W #[fg=#bd93f9]#[bg=#44475a]"
set -g window-status-format "#[fg=#f8f8f2]#[bg=#44475a]#I #W "

# status right
set -g status-right '#[fg=#8be9fd,bg=#44475a] #[fg=black,bg=#bd93f9] %H:%M | %a %b %d '
